import { BaseAgent } from "./baseAgent";
import { SandboxRunner } from "../executors/sandboxRunner";
import { generateSolutionPrompt } from "../prompts/solutionPrompts";

export interface SolutionAgentResult {
    starterCode: any;
    solutionScript: string;
    computedResults: string; // Stdout capturing final computed results
}

export class SolutionAgent extends BaseAgent {
    constructor() {
        super("gemini-2.5-flash", "You are an expert algorithms engineer who writes highly robust optimal and brute-force solution scripts.");
    }

    /**
     * Executes the LLM 5 (Solution Generation) -> SandboxRunner (Execution) -> LLM 6 (Validation/Correction) pipeline.
     */
    async generateAndVerifySolution(description: string, generationSchema: string, workingDirectory: string): Promise<SolutionAgentResult> {
        // LLM 5: Initial Solution & Schema Generation
        const initialPrompt = generateSolutionPrompt(description, generationSchema);

        // As defined in solutionPrompts.ts, this returns a strict JSON containing starter_code, solution_script
        let currentResponse = await this.generateWithReflection(initialPrompt, 1, true);
        let parsedData = JSON.parse(currentResponse);

        let currentScript = parsedData.solution_script;

        const MAX_REPAIRS = 3;
        let attempt = 0;

        while (attempt < MAX_REPAIRS) {
            try {
                console.log(`[SolutionAgent] Executing solution script attempt ${attempt + 1}...`);

                // Executor: Run the optimal solution against the inputs previously generated by scriptAgent in os.tmpdir()
                const { stdout, stderr } = await SandboxRunner.executeNodeScript(currentScript, 10000, workingDirectory); // 10s timeout robust for 15 cases

                if (stderr) {
                    console.warn(`[SolutionAgent] Execution completed but produced STDERR: ${stderr}`);
                }

                // LLM 6: Validation (implicit by checking stdout/stderr or explicitly by passing it on if needed)
                // If the run succeeded without throwing execution boundaries, we return the parsed data and outputs
                return {
                    starterCode: parsedData.starter_code,
                    solutionScript: currentScript,
                    computedResults: stdout
                };
            } catch (executionError: any) {
                console.error(`[SolutionAgent] Execution failed: ${executionError.message}`);

                attempt++;
                if (attempt >= MAX_REPAIRS) {
                    throw new Error(`SolutionAgent failed to generate a working solution script after ${MAX_REPAIRS} execution repair attempts.`);
                }

                // LLM 6 (Reflection/Repair Path): The solution crashed against the dynamic test cases. Feed trace back to fix.
                console.log(`[SolutionAgent] Requesting LLM 6 to repair the crashed solution script...`);

                const repairPrompt = `
The Node.js solution script you generated previously failed during execution in the sandbox.
Please analyze the execution runtime error and fix the Javascript logic.

PROBLEM DESCRIPTION:
"""
${description}
"""

FAILED SCRIPT CODE:
"""javascript
${currentScript}
"""

EXECUTION ERROR:
"""
${executionError.message}
"""

Return ONLY the completely fixed raw Node.js script. DO NOT WRAP IT IN MARKDOWN OR EXPLANATIONS.
`;

                // For repairs, we just want the raw JS code string back to slot into the JSON tree
                currentScript = await this.generateWithReflection(repairPrompt, 1, false);
                currentScript = this.stripMarkdownBlocks(currentScript);
            }
        }

        throw new Error("Unexpected end of SolutionAgent execution loop.");
    }

    private stripMarkdownBlocks(text: string): string {
        let clean = text.trim();
        if (clean.startsWith('```javascript')) clean = clean.replace(/^```javascript\n?/, '');
        else if (clean.startsWith('```js')) clean = clean.replace(/^```js\n?/, '');
        else if (clean.startsWith('```')) clean = clean.replace(/^```\n?/, '');

        if (clean.endsWith('```')) clean = clean.replace(/```\n?$/, '');
        return clean.trim();
    }
}
