import { Request, Response, NextFunction } from 'express';
import pg from 'pg';
import { SandboxRunner } from '../workers/executors/sandboxRunner';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';

async function fetchS3File(s3Url: string): Promise<string> {
    const s3Client = new S3Client({
        region: process.env.AWS_REGION || 'us-east-1',
        credentials: {
            accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
            secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
        }
    });
    
    const bucket = process.env.AWS_S3_BUCKET_NAME || 'oarecall-test-cases';
    const keyMatch = s3Url.match(/\.amazonaws\.com\/(.+)$/);
    if (!keyMatch) throw new Error("Invalid S3 URL format: " + s3Url);
    
    const command = new GetObjectCommand({
        Bucket: bucket,
        Key: keyMatch[1]
    });
    
    const response = await s3Client.send(command);
    if (!response.Body) return "";
    return response.Body.transformToString();
}

/**
 * Attempts to parse raw string inputs generated by LLMs or Users natively into rigorous execution JSON formats.
 * Safely handles "s = \"aabb\"", "[1, 2, 3]", and raw literal values perfectly mapped to the generated schema.
 */
function sanitizeInputToJson(inputStr: string, schema: any): string {
    if (!inputStr) return "{}";

    // 1. If it's already perfectly valid JSON (Object or Array), just return it
    try {
        const parsed = JSON.parse(inputStr);
        if (typeof parsed === 'object' && parsed !== null) {
            return inputStr;
        }
    } catch(e) {}

    // 2. Scan for LeetCode style variable assignments (e.g. `s = "aabb", t = "c"`)
    const order = schema.order || Object.keys(schema?.properties || schema || {});
    if (order.length > 0) {
        let jsonObj: any = {};
        let matchedSomething = false;

        for (const key of order) {
            // Regex match variables. Example: `s = "aabb"` captures `"aabb"`
            const regex = new RegExp(`${key}\\s*=\\s*(.+?)(?:,\\s*[a-zA-Z0-9_]+\\s*=|$|\\n)`, 'i');
            const match = inputStr.match(regex);
            
            if (match && match[1]) {
                matchedSomething = true;
                let valStr = match[1].trim();
                try {
                    // Try to parse the captured segment natively
                    jsonObj[key] = JSON.parse(valStr);
                } catch(e) {
                    // Fallback to literal string mapping
                    jsonObj[key] = valStr;
                }
            }
        }
        
        if (matchedSomething) {
            return JSON.stringify(jsonObj);
        }

        // 3. Fallback: If it's a single argument schema, aggressively wrap the entire string
        if (order.length === 1) {
            let cleanStr = inputStr.trim().replace(/^Input:\s*/i, '');
            const assignmentMatch = cleanStr.match(/^[a-zA-Z0-9_]+\s*=\s*([\s\S]*)$/);
            if (assignmentMatch) {
                cleanStr = assignmentMatch[1].trim();
            }
            
            try {
                // Try parsing whatever was extracted (e.g. `[1, 2, 3]` or `"aabb"`)
                return JSON.stringify({ [order[0]]: JSON.parse(cleanStr) });
            } catch(e) {
                // If it was just raw literal fallback `aabb` without quotes
                cleanStr = cleanStr.replace(/^["'](.*)["']$/, '$1'); 
                return JSON.stringify({ [order[0]]: cleanStr }); 
            }
        }
    }

    // Default safety fallback: Just quote the string so it's formally valid JSON
    return JSON.stringify(inputStr);
}

export const executeCode = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
        const problemId = req.params.id; // from /api/problems/:id/execute
        const { code, language, mode } = req.body;
        
        if (!problemId || !code || !mode || !language) {
            res.status(400).json({ error: "problemId, code, language, and mode are required" });
            return;
        }

        if (!['cpp', 'python', 'java'].includes(language)) {
            res.status(400).json({ error: `Language '${language}' is not supported in this phase. Please use C++, Python, or Java.` });
            return;
        }

        const { Pool } = pg;
        const pool = new Pool({ connectionString: process.env.DATABASE_URL });

        // Get Schema, Starter Code, and Examples from problem
        const probRes = await pool.query('SELECT starter_code, solution_code, ai_output FROM problems WHERE id = $1', [problemId]);
        if (probRes.rows.length === 0) {
            res.status(404).json({ error: 'Problem not found' });
            return;
        }
        const rawSchema = probRes.rows[0].solution_code;
        const schema = typeof rawSchema === 'string' ? JSON.parse(rawSchema) : rawSchema;
        const starterCodeMap = typeof probRes.rows[0].starter_code === 'string' 
            ? JSON.parse(probRes.rows[0].starter_code) 
            : probRes.rows[0].starter_code;

        const expectedStarter = starterCodeMap?.[language] || "";
        
        const aiOutput = typeof probRes.rows[0].ai_output === 'string' 
            ? JSON.parse(probRes.rows[0].ai_output) 
            : probRes.rows[0].ai_output;

        // Dynamically parse User's Class and Function names
        let userClassName = "";
        let userFuncName = "";
        
        if (language === 'cpp') {
            // e.g. class Solution { public: int firstUniqChar(string s) {
            const match = code.match(/class\s+([a-zA-Z0-9_]+)[\s\S]*?(?:public\s*:\s*)?[\w<>,:\*&\s]+\s+([a-zA-Z0-9_]+)\s*\(/);
            if (!match) {
                res.status(400).json({ error: "Could not find a valid C++ class and public method definition inside the provided code" });
                return;
            }
            userClassName = match[1];
            userFuncName = match[2];
            
            const aiMatch = expectedStarter.match(/class\s+([a-zA-Z0-9_]+)\s*{/);
            if (aiMatch && aiMatch[1] !== userClassName) {
                res.status(400).json({ error: `Class name mismatch! Expected '${aiMatch[1]}' but found '${userClassName}'.` });
                return;
            }
        } else if (language === 'python') {
            const match = code.match(/class\s+([a-zA-Z0-9_]+)[({:]?[\s\S]*?def\s+([a-zA-Z0-9_]+)\s*\(/);
            if (!match) {
                res.status(400).json({ error: "Could not find a valid Python class and 'def' method inside the provided code" });
                return;
            }
            userClassName = match[1];
            userFuncName = match[2];
            
            const aiMatch = expectedStarter.match(/class\s+([a-zA-Z0-9_]+)/);
            if (aiMatch && aiMatch[1] !== userClassName) {
                res.status(400).json({ error: `Class name mismatch! Expected '${aiMatch[1]}' but found '${userClassName}'.` });
                return;
            }
        } else if (language === 'java') {
            // e.g. class Solution { public int firstUniqChar(String s) {
            const match = code.match(/class\s+([a-zA-Z0-9_]+)\s*{[\s\S]*?(?:public|private|protected)?\s*(?:static\s+)?[\w<>[\]]+\s+([a-zA-Z0-9_]+)\s*\(/);
            if (!match) {
                res.status(400).json({ error: "Could not find a valid Java class and method definition inside the provided code" });
                return;
            }
            userClassName = match[1];
            userFuncName = match[2];
            
            const aiMatch = expectedStarter.match(/class\s+([a-zA-Z0-9_]+)\s*{/);
            if (aiMatch && aiMatch[1] !== userClassName) {
                res.status(400).json({ error: `Class name mismatch! Expected '${aiMatch[1]}' but found '${userClassName}'.` });
                return;
            }
        }

        // Fetch Test Cases
        let testCases: any[] = [];
        let exampleCases: any[] = [];
        
        // 1. Universally map exactly what the UI shows the user natively (The Examples)
        if (aiOutput?.examples && Array.isArray(aiOutput.examples)) {
            exampleCases = aiOutput.examples.map((ex: any, idx: number) => ({
                id: `example-${idx + 1}`,
                input_data: ex.input,
                expected_output: ex.output
            }));
        } else {
            // Fallback to edge cases if UI examples were not natively generated
            const edgeRes = await pool.query('SELECT * FROM test_cases WHERE problem_id = $1 AND type = $2', [problemId, 'edge']);
            exampleCases = edgeRes.rows;
        }

        if (mode === 'run') {
            testCases = exampleCases;
            if (testCases.length > 3) testCases = testCases.slice(0, 3);
            
        } else {
            // mode === 'submit': evaluate SAME EXACT UI examples + all hidden massive test cases from S3 concurrently
            const submitRes = await pool.query('SELECT * FROM test_cases WHERE problem_id = $1 AND type = $2 ORDER BY id ASC', [problemId, 'large_tle']);
            testCases = [...exampleCases, ...submitRes.rows];
        }

        const results = [];
        let allPassed = true;

        for (let i = 0; i < testCases.length; i++) {
            const tc = testCases[i];
            
            let inputJsonStr = tc.input_data;
            let expectedOutputStr = tc.expected_output;

            // If it's a S3 file (large_tle), fetch it securely via AWS SDK
            if (!inputJsonStr && tc.input_file_url) {
                inputJsonStr = await fetchS3File(tc.input_file_url);
            }
            if (!expectedOutputStr && tc.output_file_url) {
                expectedOutputStr = await fetchS3File(tc.output_file_url);
            }

            // Sanitize unverified AI/DB text inputs strictly into schema-mapped JSON 
            const sanitizedInputStr = sanitizeInputToJson(inputJsonStr || "", schema);

            // Execute safely through Language Isolated Sandbox
            const execRes = await SandboxRunner.executeUserCode(code, language, userClassName, userFuncName, schema, sanitizedInputStr, 3000);

            let passed = false;
            let expectedClean = expectedOutputStr ? expectedOutputStr.trim() : "";
            let userOutputClean = undefined;

            if (execRes.success && execRes.result !== undefined) {
                userOutputClean = JSON.stringify(execRes.result);
                try {
                    // Deep comparison approach via stringify of parsed values (normalizes spacing)
                    if (userOutputClean === expectedClean) {
                        passed = true;
                    } else if (JSON.stringify(JSON.parse(userOutputClean)) === JSON.stringify(JSON.parse(expectedClean))) {
                        passed = true;
                    }
                } catch(e) {
                    // Fallback to strict string check if parsing as JSON fails (e.g. raw strings)
                    if (userOutputClean === expectedClean) {
                        passed = true;
                    }
                }
            }

            if (!passed || !execRes.success) {
                allPassed = false;
            }

            results.push({
                testCaseId: tc.id,
                passed: passed,
                runtimeMs: execRes.runtimeMs,
                expectedOutput: expectedClean,
                userOutput: userOutputClean,
                stdout: execRes.stdout,
                stderr: execRes.stderr,
                error: execRes.error,
                // Pass raw input for the frontend UI snippet preview
                inputSnippet: inputJsonStr ? inputJsonStr.substring(0, 100) + (inputJsonStr.length > 100 ? '...' : '') : ''
            });

            // If submit mode and we fail one, break early
            if (mode === 'submit' && !passed) {
                break;
            }
        }

        res.status(200).json({
            success: true,
            allPassed,
            results: results
        });

    } catch (error: any) {
        console.error('[ExecuteController] Execution Error:', error);
        next(error);
    }
};
