import { Request, Response, NextFunction } from 'express';
import { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { SandboxRunner } from '../workers/executors/sandboxRunner';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';

async function fetchS3File(s3Url: string): Promise<string> {
    const s3Client = new S3Client({
        region: process.env.AWS_REGION || 'us-east-1',
        credentials: {
            accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
            secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
        }
    });

    const bucket = process.env.AWS_S3_BUCKET_NAME || 'oarecall-test-cases';
    const keyMatch = s3Url.match(/\.amazonaws\.com\/(.+)$/);
    if (!keyMatch) throw new Error("Invalid S3 URL format: " + s3Url);

    const command = new GetObjectCommand({
        Bucket: bucket,
        Key: keyMatch[1]
    });

    const response = await s3Client.send(command);
    if (!response.Body) return "";
    return response.Body.transformToString();
}

/**
 * Attempts to parse raw string inputs generated by LLMs or Users natively into rigorous execution JSON formats.
 */
function sanitizeInputToJson(inputStr: string, schema: any): string {
    if (!inputStr) return "{}";

    let order = schema?.order;
    if (!order) {
        const propKeys = Object.keys(schema?.properties || {});
        if (propKeys.length > 0) {
            order = propKeys;
        } else if (schema?.type && typeof schema.type === 'string' && schema.type !== 'object') {
            order = ['single_arg'];
        } else {
            const realKeys = Object.keys(schema || {}).filter((k: string) => !['type', 'minDepth', 'maxDepth', 'edgeCases', 'minLength', 'maxLength', 'minSize', 'maxSize', 'minVal', 'maxVal', 'minN', 'maxN', 'min', 'max', 'min_depth', 'max_depth', 'null_probability', 'cases', 'items', 'order', 'properties'].includes(k));
            order = realKeys.length > 0 ? realKeys : ['single_arg'];
        }
    }
    let isSingleArg = order.length === 1 && order[0] === 'single_arg';

    // Fast path: already valid JSON
    try {
        const parsed = JSON.parse(inputStr);
        if (typeof parsed === 'object' && parsed !== null) {
            if (isSingleArg) return JSON.stringify([parsed]);
            return inputStr;
        }
    } catch (e: any) { }

    // Bracket-aware key=value parser — correctly handles nested arrays/objects.
    // e.g. "n = 5, edges = [[0,1],[0,2],[0,3],[1,4]]"  won't break on inner commas.
    function parseKV(str: string): Record<string, string> | null {
        const result: Record<string, string> = {};
        str = str.trim().replace(/^Input:\s*/i, '');
        let i = 0;
        while (i < str.length) {
            while (i < str.length && (str[i] === ',' || str[i] === ' ' || str[i] === '\n')) i++;
            if (i >= str.length) break;
            const keyMatch = str.slice(i).match(/^([a-zA-Z0-9_]+)\s*=/);
            if (!keyMatch) return null;
            const key = keyMatch[1];
            i += keyMatch[0].length;
            while (i < str.length && str[i] === ' ') i++;
            const start = i;
            let depth = 0;
            while (i < str.length) {
                const c = str[i];
                if (c === '[' || c === '(' || c === '{') depth++;
                else if (c === ']' || c === ')' || c === '}') depth--;
                else if (c === ',' && depth === 0) break;
                i++;
            }
            result[key] = str.slice(start, i).trim();
        }
        return Object.keys(result).length > 0 ? result : null;
    }

    const kvPairs = parseKV(inputStr);
    if (kvPairs) {
        const foundKeys = Object.keys(kvPairs);

        // Prefer schema order if ALL its keys are present in the input; otherwise use input key order.
        // This handles the case where schema has different param names than the example input string.
        const schemaMatches = !isSingleArg && order.length > 0 && order.every((k: string) => k === 'single_arg' || kvPairs[k] !== undefined);
        const resolvedOrder = schemaMatches ? order : foundKeys;

        if (resolvedOrder.length > 0) {
            const argsArr: any[] = [];
            for (const key of resolvedOrder) {
                const k = key === 'single_arg' ? foundKeys[0] : key;
                const valStr = kvPairs[k];
                if (valStr === undefined) continue;
                try { argsArr.push(JSON.parse(valStr)); } catch (e: any) { argsArr.push(valStr); }
            }
            if (argsArr.length > 0) return JSON.stringify(argsArr);
        }
    }

    // Fallback for single-arg: strip "key =" prefix and parse raw value
    if (isSingleArg || order.length === 1) {
        let cleanStr = inputStr.trim().replace(/^Input:\s*/i, '');
        const m = cleanStr.match(/^[a-zA-Z0-9_]+\s*=\s*([\s\S]*)$/);
        if (m) cleanStr = m[1].trim();
        try { return JSON.stringify([JSON.parse(cleanStr)]); }
        catch (e: any) { return JSON.stringify([cleanStr.replace(/^["'](.*)['"]$/, '$1')]); }
    }

    return JSON.stringify([inputStr]);
}

export const executeCode = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
        const problemId = req.params.id;
        const { code, language, mode } = req.body;

        if (!problemId || !code || !mode || !language) {
            res.status(400).json({ error: "problemId, code, language, and mode are required" });
            return;
        }

        if (!['cpp', 'python', 'java'].includes(language)) {
            res.status(400).json({ error: `Language '${language}' is not supported.` });
            return;
        }

        const pool = new Pool({ connectionString: process.env.DATABASE_URL });

        const probRes = await pool.query(
            'SELECT starter_code, solution_code, ai_output, time_limit_ms FROM problems WHERE id = $1',
            [problemId]
        );
        if (probRes.rows.length === 0) {
            res.status(404).json({ error: 'Problem not found' });
            return;
        }
        // Java-baseline time limit per test case (ms). Default 2000ms for legacy problems.
        const timeLimitMsJava: number = probRes.rows[0].time_limit_ms ?? 2000;
        const rawSchema = probRes.rows[0].solution_code;
        const schema = typeof rawSchema === 'string' ? JSON.parse(rawSchema) : rawSchema;
        const starterCodeMap = typeof probRes.rows[0].starter_code === 'string'
            ? JSON.parse(probRes.rows[0].starter_code)
            : probRes.rows[0].starter_code;

        const expectedStarter = starterCodeMap?.[language] || "";

        let userClassName = "";
        let userFuncName = "";
        let returnTypeStr = "";

        // Strip block and line comments BEFORE scanning for class/function names.
        // Use expectedStarter if available to strictly guarantee original signature typings
        const codeForParsing = (expectedStarter || code)
            .replace(/\/\*[\s\S]*?\*\//g, '')  // remove /* ... */ blocks
            .replace(/\/\/[^\n]*/g, '')          // remove // line comments
            .replace(/#[^\n]*/g, '');            // remove # line comments (Python)

        if (language === 'cpp') {
            const match = codeForParsing.match(/class\s+([a-zA-Z0-9_]+)[\s\S]*?(?:public\s*:\s*)?([\w<>,:*&\s]+)\s+([a-zA-Z0-9_]+)\s*\(/);
            if (!match) {
                res.status(400).json({ error: "Invalid C++ definition" });
                return;
            }
            userClassName = match[1];
            returnTypeStr = match[2];
            userFuncName = match[3];
        } else if (language === 'python') {
            const match = codeForParsing.match(/class\s+([a-zA-Z0-9_]+)[({:]?[\s\S]*?def\s+([a-zA-Z0-9_]+)\s*\([\s\S]*?\)\s*(?:->\s*([\w\[\] ,]+))?:/);
            if (!match) {
                res.status(400).json({ error: "Invalid Python definition" });
                return;
            }
            userClassName = match[1];
            userFuncName = match[2];
            returnTypeStr = match[3] || "";
        } else if (language === 'java') {
            // Prefer matching 'class Solution' explicitly (almost all LeetCode Java uses this)
            const solutionMatch = codeForParsing.match(/class\s+Solution\s*(?:implements[^{]*)?\s*\{[\s\S]*?(?:public|private|protected)?\s*(?:static\s+)?([\w<>[\]]+)\s+([a-zA-Z0-9_]+)\s*\(/);
            if (solutionMatch) {
                userClassName = 'Solution';
                returnTypeStr = solutionMatch[1];
                userFuncName = solutionMatch[2];
            } else {
                const fallback = codeForParsing.match(/class\s+([a-zA-Z0-9_]+)\s*\{[\s\S]*?(?:public|private|protected)?\s*(?:static\s+)?([\w<>[\]]+)\s+([a-zA-Z0-9_]+)\s*\(/);
                if (!fallback) {
                    res.status(400).json({ error: "Invalid Java definition" });
                    return;
                }
                userClassName = fallback[1];
                returnTypeStr = fallback[2];
                userFuncName = fallback[3];
            }
        }

        function normalizeReturnType(rt: string): string {
            if (!rt) return 'unknown';
            rt = rt.trim().toLowerCase();
            if (rt.includes('[') || rt.includes('<') || rt.includes('vector') || rt.includes('list') || rt.includes('array') || rt.includes('node')) return 'array';
            if (['int', 'long', 'double', 'float', 'short', 'integer', 'number'].some(p => rt.includes(p))) return 'number';
            if (['string', 'str', 'char'].some(p => rt.includes(p))) return 'string';
            if (['boolean', 'bool'].some(p => rt.includes(p))) return 'boolean';
            return 'object'; 
        }
        const expectedPrimitiveType = normalizeReturnType(returnTypeStr);

        let testCases: any[] = [];
        let exampleCases: any[] = [];

        const aiOutput = typeof probRes.rows[0].ai_output === 'string'
            ? JSON.parse(probRes.rows[0].ai_output)
            : probRes.rows[0].ai_output;

        if (aiOutput?.examples && Array.isArray(aiOutput.examples)) {
            exampleCases = aiOutput.examples.map((ex: any, idx: number) => ({
                id: `example-${idx + 1}`,
                input_data: ex.input,
                expected_output: ex.output
            }));
        }

        if (mode === 'run') {
            testCases = exampleCases.slice(0, 3);
        } else {
            const submitRes = await pool.query('SELECT * FROM test_cases WHERE problem_id = $1 AND type = $2 ORDER BY id ASC', [problemId, 'large_tle']);
            testCases = [...exampleCases, ...submitRes.rows];
        }

        const preppedCases = await Promise.all(testCases.map(async (tc) => {
            let inputJsonStr = tc.input_data;
            let expectedOutputStr = tc.expected_output;
            if (!inputJsonStr && tc.input_file_url) inputJsonStr = await fetchS3File(tc.input_file_url);
            if (!expectedOutputStr && tc.output_file_url) expectedOutputStr = await fetchS3File(tc.output_file_url);

            return {
                tc,
                originalInputStr: inputJsonStr,
                sanitizedInputStr: sanitizeInputToJson(inputJsonStr || "", schema),
                expectedClean: expectedOutputStr ? expectedOutputStr.trim() : ""
            };
        }));

        // Per-language multipliers relative to Java baseline
        const LANGUAGE_MULTIPLIER: Record<string, number> = {
            java: 1.0,
            cpp: 0.5,   // native ≈ 2× faster than Java
            python: 5.0,   // CPython ≈ 5× slower than Java
        };
        const adjustedLimitMs = Math.round(timeLimitMsJava * (LANGUAGE_MULTIPLIER[language] ?? 1.0));

        const batchInputs = preppedCases.map(p => p.sanitizedInputStr);
        // Wall clock is 60s (infrastructure). TLE is detected via measured runtimeMs below.
        const batchResults = await SandboxRunner.executeUserCode(code, language, userClassName, userFuncName, schema, batchInputs, 60000);

        // Post-execution per-function TLE check (applies to both run and submit).
        // runtimeMs is measured ONLY around the user's function call in driver code.
        for (let i = 0; i < batchResults.length; i++) {
            const r = batchResults[i];
            if (r?.success && typeof r.runtimeMs === 'number' && r.runtimeMs > adjustedLimitMs) {
                batchResults[i] = {
                    success: false,
                    error: `Time Limit Exceeded: function took ${Math.round(r.runtimeMs)}ms (limit: ${adjustedLimitMs}ms for ${language})`
                };
            }
        }

        const results = [];
        let allPassed = true;

        for (let i = 0; i < preppedCases.length; i++) {
            const prep = preppedCases[i];
            const execRes = batchResults[i] || { success: false, error: "Result missing." };

            let passed = false;
            let userOutputClean = execRes.result !== undefined ? JSON.stringify(execRes.result) : undefined;

            if (execRes.success && userOutputClean !== undefined) {
                try {
                    let parsedExp = JSON.parse(prep.expectedClean);
                    
                    if (expectedPrimitiveType === 'number' && typeof parsedExp === 'string') {
                        if (!isNaN(Number(parsedExp))) parsedExp = Number(parsedExp);
                    } else if (expectedPrimitiveType === 'string' && typeof parsedExp === 'number') {
                        parsedExp = String(parsedExp);
                    } else if (expectedPrimitiveType === 'boolean' && typeof parsedExp === 'string') {
                        if (parsedExp.toLowerCase() === 'true') parsedExp = true;
                        if (parsedExp.toLowerCase() === 'false') parsedExp = false;
                    } else if ((expectedPrimitiveType === 'array' || expectedPrimitiveType === 'object') && typeof parsedExp === 'string') {
                        try { parsedExp = JSON.parse(parsedExp); } catch (e) {}
                    }
                    
                    const normalizedExpectedString = JSON.stringify(parsedExp);

                    if (userOutputClean === prep.expectedClean || userOutputClean === normalizedExpectedString || JSON.stringify(JSON.parse(userOutputClean)) === normalizedExpectedString) {
                        passed = true;
                    }
                } catch (e: any) {
                    if (userOutputClean === prep.expectedClean) passed = true;
                }
            }

            if (!passed || !execRes.success) allPassed = false;

            results.push({
                testCaseId: prep.tc.id,
                passed,
                runtimeMs: execRes.runtimeMs,
                expectedOutput: prep.expectedClean,
                userOutput: userOutputClean,
                error: execRes.error,
                inputSnippet: prep.originalInputStr?.substring(0, 100)
            });

            if (mode === 'submit' && !passed) break;
        }

        if (mode === 'submit') {
            try {
                let status = allPassed ? 'Accepted' : 'Wrong Answer';
                if (!allPassed) {
                    const failed = results.find(r => !r.passed);
                    if (failed?.error?.includes('Time Limit Exceeded')) status = 'Time Limit Exceeded';
                    else if (failed?.error) status = 'Runtime Error';
                }
                const avgRuntime = results.length > 0 ? Math.round(results.reduce((s, r) => s + (r.runtimeMs || 0), 0) / results.length) : null;

                // Extract user_id from JWT token in cookies
                let userId = null;
                const token = req.cookies.token;
                if (token) {
                    try {
                        const decoded: any = jwt.verify(token, process.env.JWT_SECRET || 'fallback_secret');
                        userId = decoded.userId;
                    } catch (e: any) {
                        console.error('[ExecuteController] JWT verify failed:', e.message);
                    }
                }

                await pool.query(
                    `INSERT INTO submissions (problem_id, user_id, language, code, status, runtime_ms, submitted_at)
                     VALUES ($1, $2, $3, $4, $5, $6, NOW())`,
                    [problemId, userId, language, code, status, avgRuntime]
                );
            } catch (dbErr) {
                console.error('[ExecuteController] Failed to persist submission:', dbErr);
            }
        }

        res.status(200).json({ success: true, allPassed, results });
        await pool.end();
    } catch (error: any) {
        console.error('[ExecuteController] Error:', error);
        next(error);
    }
};
